### ISSUE TITLE
PyTorch Lightning version

### ISSUE THREAD

**Issue by EmreOzkose** [Spijkervet/CLMR#19]
Hi,

When I followed [these steps](https://github.com/Spijkervet/CLMR#pre-train-on-your-own-folder-of-audio-files) to test pre-trained model, I got this error:
```
(clmr) yunusemre.ozkose@server:/CLMR$ python main.py --dataset audio --dataset_dir /path/to/test_audio_dataset_dir
Global seed set to 42
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    module = module.load_from_checkpoint(
  File "/miniconda3/envs/cmlr/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 137, in load_from_checkpoint
    return _load_from_checkpoint(
  File "/miniconda3/envs/cmlr/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/miniconda3/envs/cmlr/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 250, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 1 required positional argument: 'args'
```
There was [a related bug](https://github.com/Lightning-AI/lightning/issues/2909) in Lightning that seems to be solved. Could you state your PyTorch Lightning version?

**Comment by ee-jw** [comment]
have you solved this issue? I'm having trouble with this same issue.

**Comment by EmreOzkose** [comment]
Hi @ee-jw , actually I even don't remember where/when I used this model, sorry.
